export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="pt">
            <body className="bg-red-200">{children}</body>
        </html>
    )
}
